baseURL: 'https://justinmitchel.com/'
languageCode: 'en-us'
# copyright: 'justinmitchel.com'
title: 'Justin Mitchel'
theme: "PaperMod"
enableEmoji: true
rssLimit: 20
copyright: "2022 Justin Mitchel. All rights reserved"

author:
  name: Justin Mitchel

menu:
  main:
    - identifier: blog
      name: blog
      url: /
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    - identifier: cfe
      name: work
      url: https://www.cfe.sh
      weight: 30



      
params:
    AuthorName: Justin Mitchel
    homeInfoParams:
        Title: Hi, I'm Justin
        Content: |
          I am a father, entrepreneur, coder, engineer, teacher, & student of life. 
          I teach on [cfe](https://www.cfe.sh/).
    socialIcons: 
      - name: "twitter"
        url: "https://twitter.com/justinmitchel"
      - name: "tiktok"
        url: "https://www.tiktok.com/@justinmitchel"
      - name: "github"
        url: "https://www.github.com/jmitchel3"
      - name: "youtube"
        url: "https://www.youtube.com/@justinmitchel"
      - name: "linkedin"
        url: "https://www.linkedin.com/in/justinmitchel"
    defaultTheme: dark
    ShowReadingTime: true
    ShowToc: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    comments: false
    author: ["Justin Mitchel"]
    ShowShareButtons: false
    ShareButtons: ["linkedin", "twitter"]
    
